esphome:
  name: wasserzaehler
  friendly_name: Wasserzähler
  area: Heizungskeller
  on_boot:
    - priority: -100
      then:
        - pulse_meter.set_total_pulses:
            id: wasser_puls
            value: !lambda "return id(wasser_total_saved) / 0.001;"

esp8266:
  board: d1_mini

globals:
  - id: wasser_total_saved
    type: float
    restore_value: yes
    update_interval: 1h
    initial_value: "0"

# Enable logging
logger:

time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_password

ota:
  - platform: esphome
    id: wasserzaehler_ota
    encryption:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wasserzaehler Fallback Hotspot"
    password: "notasecret"

mqtt:
  broker: 192.168.0.7
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret notasecret
    type: digest
sensor:
  - platform: pulse_meter
    pin:
      number: GPIO12 # Entspricht D6 auf dem D1 Mini
      mode: INPUT_PULLUP # Aktiviert internen Pullup-Widerstand für Reedschalter
    id: wasser_puls
    name: "Wasser Durchfluss raw"
    internal: true
    unit_of_measurement: "L/min"
    icon: "mdi:water"
    timeout: 20s
    internal_filter: 5s # Debounce -> wirkt auch auf das Total (100ms = nur Prellen)
    
    total:
      name: "Water Meter Total"
      unit_of_measurement: "m³"
      id: water_meter_total
      accuracy_decimals: 3
      device_class: water
      state_class: total_increasing
      filters:
        - multiply: 0.001
      on_value:
        - lambda: |-
            id(wasser_total_saved) = x;

  - platform: copy
    source_id: wasser_puls
    name: "Wasser Durchfluss"
    id: wasser_durchfluss
    unit_of_measurement: "L/min"
    icon: "mdi:water"
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 6

  - platform: copy
    source_id: wasser_puls
    name: "Impulses per Second"
    id: impulses_per_second
    unit_of_measurement: "imp/s"
    icon: "mdi:pulse"
    accuracy_decimals: 3
    state_class: measurement
    filters:
      - multiply: 0.01666667

number:
  - platform: template
    name: "Wasserzähler Zählerstand"
    id: wasserzaehler_stand
    unit_of_measurement: "m³"
    icon: "mdi:water"
    min_value: 0
    max_value: 1000000
    step: 0.001
    mode: box
    optimistic: true
    restore_value: false
    on_value:
      - globals.set:
          id: wasser_total_saved
          value: !lambda "return x;"
      - pulse_meter.set_total_pulses:
          id: wasser_puls
          value: !lambda "return x / 0.001;"

